services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    networks:
      - back-tier
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

#  command-processor:
#    container_name: command-processor
#    image: command-processor:0.0.1-SNAPSHOT
#    networks:
#      - back-tier
#    ports:
#      - "8080"

#volumes:
#  db-data:
#    driver: flocker
#    driver_opts:
#      size: "10GiB"

#configs:
#  httpd-config:
#    external: true
#
#secrets:
#  server-certificate:
#    external: true

networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  back-tier: {}