services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:management
    networks:
      - back-tier
    ports:
      - "5672:5672"
      - "15672:15672"
    tmpfs:
      - /var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: gurps


#  command-processor:
#    container_name: command-processor
#    image: command-processor:0.0.1-SNAPSHOT
#    networks:
#      - back-tier
#    ports:
#      - "8080"

#volumes:
#  db-data:
#    driver: flocker
#    driver_opts:
#      size: "10GiB"

#configs:
#  httpd-config:
#    external: true
#
#secrets:
#  server-certificate:
#    external: true

networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  back-tier: {}